language: node_js
node_js:
- '0.10'
before_deploy:
- npm install ws browserify coffeeify
- mkdir -p deploy/gateblu-websocket/latest
- mkdir -p deploy/gateblu-websocket/$TRAVIS_TAG
- node_modules/.bin/browserify -t coffeeify -s GatebluWebsocket index.js > deploy/gateblu-websocket/latest/gateblu-websocket.js
- cp deploy/gateblu-websocket/latest/gateblu-websocket.js deploy/gateblu-websocket/$TRAVIS_TAG/gateblu-websocket.js
- gzip deploy/gateblu-websocket/latest/gateblu-websocket.js
- mv deploy/gateblu-websocket/latest/gateblu-websocket.js.gz deploy/gateblu-websocket/latest/gateblu-websocket.js
- cp deploy/gateblu-websocket/latest/gateblu-websocket.js deploy/gateblu-websocket/$TRAVIS_TAG/gateblu-websocket.js
deploy:
  provider: s3
  access_key_id: AKIAJH2D5IPIRHYJT5IA
  secret_access_key:
    secure: "fhNJGUgmYHbijY2lSwhQWNBTj+h4SL+xxHIv2UHfmHNe3QegTJgCTgQNri3lT/C/W7TGdMaOynLLKJwxyOIDOQVYB23NiM+tWGxR2f/0fTQ9QUKlzIAiZcTj/wkqOnWXcQYi/Y3BudAetT2tR5NARtBa3ZN3JGgeF1sZDD/Vf0g="
  bucket: octoblu-cdn
  region: us-west-2
  detect_encoding: true
  skip_cleanup: true
  local-dir: deploy
  upload-dir: js
  on:
    tags: true
    all_branches: true
